"""add time for cash_in_out table

Revision ID: 73c8775614d1
Revises: 0b9b26eb2f2c
Create Date: 2024-08-07 02:22:18.583719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73c8775614d1'
down_revision: Union[str, None] = '0b9b26eb2f2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cash_in_outs', sa.Column('time', sa.Time(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cash_in_outs', 'time')
    # ### end Alembic commands ###
