services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${APP_DB__POSTGRES__USER:?}
      POSTGRES_PASSWORD: ${APP_DB__POSTGRES__PASSWORD:?}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - backend
    restart: unless-stopped

  main-app:
    build:
      context: .
      dockerfile: cashier_app/.DockerFile
    container_name: main-app
    ports:
      - "${API_PORT}:8000"
    env_file:
      - .env
    volumes:
      - ./cashier_app:/cashier_app
    networks:
      - backend
    depends_on:
      - postgres
    command: "uvicorn main:app --reload --host 0.0.0.0 --port 8000"


networks:
  backend:
    driver: bridge

volumes:
    postgres: